MODEL: 
  DATA_DIM: 100
  SEQ_LEN: 100
  TYPE: FFN-KL # options: {FFN-KL, GAN}
  HIDDEN_DIM: 50
  ALIGN_DATA: factors # options: {gen_states, factors, rates}
  DAYK_LFADS_TRAINABLES: # options: any LFADS layers
    - lowd_readin
    # - decoder.rate_linear
TRAIN:
  DATA: 
    DAY0: ''
    DAYK: ''
  PATIENCE: 50
  BATCH_SIZE: 4000
  MAX_EPOCHS: 10000
  MAX_GRAD_NORM: 200.0
  ADAM_EPSILON: 1.0e-8 
  GAN:
    DISC_TRAIN_DELAY: 1
    BATCH_DISC: True
    LABEL_SMOOTH: True
    DISC_LR:
      INIT: 0.001
      STOP: 1.0e-10
      DECAY: 0.98
      PATIENCE: 6
  NLL_WEIGHT: 0.0 # can prob apply this for any type of alignment network
  LR:
    INIT: 0.001
    STOP: 1.0e-10
    DECAY: 0.98
    PATIENCE: 6
  USE_TB: True
  MODEL_DIR: /snel/home/asedler/ray_results/pbt_jango_day0/best_model
  ALIGN_DIR: /snel/home/asedler/ray_results/align_jango_GAN
  OVERWRITE: True
  