MODEL:
  DATA_DIM: 100
  SEQ_LEN: 100
  ENCODER_INPUT_DIM: 50
  SMART_INIT: False
  IC_ENC_DIM: 100
  CI_ENC_DIM: 100
  CON_DIM: 100
  CO_DIM: 4
  IC_DIM: 100
  GEN_DIM: 100
  FAC_DIM: 30
  DROPOUT_RATE: 0.1 # PBT
  CD_RATE: 0.5 # PBT
TRAIN:
  DATA:
    DIR: ''
    PREFIX: lfads
    AUGMENT:
      JITTER_WIDTH: 2
  PATIENCE: 10
  BATCH_SIZE: 1000
  ADAM_EPSILON: 1.0e-8
  FIX_READIN: False
  LR: 
    INIT: 1.0e-3 # PBT
    STOP: 1.0e-5 # note - this was changed arbitrarily just so I could train models faster!!!
    DECAY: 0.95  # note - this was changed arbitrarily just so I could train models faster!!!
  L2:
    INCREASE_EPOCH: 10 # note - this was changed arbitrarily just so I could train models faster!!!
    GEN_SCALE: 1.0e-6 # PBT
    CON_SCALE: 1.0e-6 # PBT
  KL:
    INCREASE_EPOCH: 10 # note - this was changed arbitrarily!!!
    IC_WEIGHT: 1.0e-6 # PBT
    CO_WEIGHT:  1.0e-6 # PBT
  TUNE_MODE: True
  OVERWRITE: True
  PBT_MODE: True
  USE_TB: False
  MODEL_DIR: ~/tmp/lfads_tf2/nomad
